version: '3.9'
services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes: [ "..:/workspaces:cached" ]
    command: sleep infinity
    networks: [ devnet ]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: faith_service
    ports: [ "5432:5432" ]
    networks: [ devnet ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
networks:
  devnet: {}
